### ISSUE TITLE
README does not tell me how I can see it run, or how to clone it and make it run for myself

### ISSUE THREAD

**Issue by MichaelKentBurns** [bahati7/faq-accordion-main-react#1]
You documented some about how you build it, but does not provide a link to a running deployment.
I would want to see it running for myself, or at least know how to clone it and run it on my own machine. 

Also, what I'm really interested in for this exercise is to see you actually making changes to the code to add enhancements or fix bugs.  

If I could run it, then I might be able to evaluate it and identify issues that need fixing.
That is the point of this challenge.     

If you can do that to some degree I'll say that this challenge was met.  
But short of that, it appears to me that you followed a tutorial and got part way done.

**Comment by bahati7** [comment]
Thanks for the feedback. I understand wanting to see it live.

This article explains cloning a React app from GitHub and running it locally : [https://www.geeksforgeeks.org/how-to-download-a-react-project-from-github-and-run-in-my-pc/].

The Readme was auto-generated during setup.

**Comment by MichaelKentBurns** [comment]
Much better! Thank you.
